package("void_pointer")
    set_homepage("https://github.com/MrowrLib/void_pointer.h")
    set_description("A header-only library for memory-managed void pointers.")
    add_urls("https://github.com/MrowrLib/void_pointer.h.git")
    add_deps("managed_pointer")
    on_install(function (package)
        os.cp("include", package:installdir())
    end)
