package("_Log_")
    set_homepage("https://github.com/MrowrLib/_Log_.h")
    set_description("A header-only library for simple logging.")
    add_urls("https://github.com/MrowrLib/_Log_.cpp.git")
    on_install(function (package)
        os.cp("include", package:installdir())
    end)
