package("specs_cpp")
    set_homepage("https://github.com/mrowrpurr/Specs.cpp")
    set_description("Async BDD C++ Test Framework.")
    add_urls("https://github.com/mrowrpurr/Specs.cpp.git")
    add_deps("string_format")
    on_install(function (package)
        os.cp("include", package:installdir())
    end)
