package("dll_injector")
    set_homepage("https://github.com/MrowrLib/dll_injector.h")
    set_description("A header-only library for easily injecting .dll's into running Windows processes.")
    add_urls("https://github.com/MrowrLib/dll_injector.git")
    add_deps("_Log_")
    on_install(function (package)
        os.cp("include", package:installdir())
    end)
