package("libfalltergeist")
    set_homepage("https://github.com/falltergeist/libfalltergeist")
    set_description("C++ library which allows to work with Fallout(tm) data files")
    add_urls("https://github.com/falltergeist/libfalltergeist.git")
    add_deps("zlib")
    add_deps("cmake")
    on_install(function (package)
        import("package.tools.cmake").install(package, {})
    end)
